# Generated by Django 4.2.1 on 2023-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='dob',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='patronym',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
