# Generated by Django 4.2.1 on 2023-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_alter_schedule_options_alter_commonuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='username',
        ),
    ]
