# Generated by Django 4.2.1 on 2023-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_remove_commonuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='patronym',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], verbose_name='День недели:'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(max_length=5, verbose_name='Конец приема'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(max_length=5, verbose_name='Начало приема'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='about',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание'),
        ),
    ]
