# Generated by Django 4.2.1 on 2023-05-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_alter_commonuser_dob_alter_commonuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toothcard',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='toothcard',
            name='patient',
        ),
        migrations.AddField(
            model_name='toothcard',
            name='visit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dental.visit', verbose_name='Прием'),
        ),
    ]
